kind: Pod
apiVersion: v1
metadata:
  name: kubernetes-bootcamp-9bc58d867-sx9c9
  generateName: kubernetes-bootcamp-9bc58d867-
  namespace: default
  uid: b6d29090-3c1d-4716-877c-a54df8ad7766
  resourceVersion: '18365'
  creationTimestamp: '2025-01-31T12:34:22Z'
  labels:
    app: kubernetes-bootcamp
    pod-template-hash: 9bc58d867
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: kubernetes-bootcamp-9bc58d867
      uid: 8746c313-164c-4576-8af0-c37e73210a43
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2025-01-31T12:34:22Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:generateName: {}
          f:labels:
            .: {}
            f:app: {}
            f:pod-template-hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"8746c313-164c-4576-8af0-c37e73210a43"}: {}
        f:spec:
          f:containers:
            k:{"name":"kubernetes-bootcamp"}:
              .: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:name: {}
              f:resources: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext: {}
          f:terminationGracePeriodSeconds: {}
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2025-01-31T12:34:24Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"PodReadyToStartContainers"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:hostIPs: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"10.244.0.24"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      subresource: status
spec:
  volumes:
    - name: kube-api-access-t956v
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
  containers:
    - name: kubernetes-bootcamp
      image: gcr.io/google-samples/kubernetes-bootcamp:v1
      resources: {}
      volumeMounts:
        - name: kube-api-access-t956v
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  nodeName: minikube
  securityContext: {}
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
status:
  phase: Running
  conditions:
    - type: PodReadyToStartContainers
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2025-01-31T12:34:24Z'
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2025-01-31T12:34:22Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2025-01-31T12:34:24Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2025-01-31T12:34:24Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2025-01-31T12:34:22Z'
  hostIP: 192.168.59.100
  hostIPs:
    - ip: 192.168.59.100
  podIP: 10.244.0.24
  podIPs:
    - ip: 10.244.0.24
  startTime: '2025-01-31T12:34:22Z'
  containerStatuses:
    - name: kubernetes-bootcamp
      state:
        running:
          startedAt: '2025-01-31T12:34:23Z'
      lastState: {}
      ready: true
      restartCount: 0
      image: gcr.io/google-samples/kubernetes-bootcamp:v1
      imageID: >-
        docker-pullable://gcr.io/google-samples/kubernetes-bootcamp@sha256:0d6b8ee63bb57c5f5b6156f446b3bc3b3c143d233037f3a2f00e279c8fcc64af
      containerID: >-
        docker://ba84c6c595a90699808197b1552a5cf7ea55481d468d19d2fe2f015af492ecf4
      started: true
      volumeMounts:
        - name: kube-api-access-t956v
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
          recursiveReadOnly: Disabled
  qosClass: BestEffort
